### ISSUE TITLE
Proper UI components

### ISSUE THREAD

**Issue by rituisboy** [ariflogs/RetroUI#5]
I think for properly making ui component that is customizable by other developers for their uses we need to use clsx, tailwind-merge, and cva for proper class names and we need to follow compound components design pattern

**Comment by ariflogs** [comment]
yes, good suggestions. I was planning to add `clsx` in the next release. but as far as the design pattern, I'm not sure yet. I am studying the codebases of some other tailwind UI libraries.

compound components design pattern make it a React-focused library?

**Comment by ariflogs** [comment]
I see, makes sense. I'll add a code style guide based on this soon.

**Comment by ariflogs** [comment]
Implemented a proper design system with new does and installation guide, please checkout the `avatar` component for details.
